### ISSUE TITLE
Access Postgresql files

### ISSUE THREAD

**Issue by Kurs270** [Expaso/hassos-addons#44]
Hi, 
I am running homeassistant os and installed the TimeScaleDB addon.
Now  I would like to make some changes to the postgres configuration (especially pg_hba.conf).
I cannot, however, find these files. I have the ssh addon installed, but when I connect via ssh I seem to end up in some "jail" where I cannot see the whole file system.
a
   cd /
   find . -name pg_hba.conf 
yields - nothing
Any chance to access the postgres files?

BTW... this addon is really great work.

**Comment by expaso** [comment]
Hi @Kurs270 , 

Yes, addons have separate storage-folders mounted to them. 
The SSH addon cannot access these folders, because you need root-rights to do so.

There are basically 2 options:

1) Gain SSH root-access using this method: https://developers.home-assistant.io/docs/operating-system/debugging/
    Once logged in,  you can find all storage folders for all addons here: `/mnt/data/supervisor/addons/data/`
    This also works when the container is not running.
   
2) Buy opening a new shell using the ssh-addon, and run a bash-shell within the running addon using this docker command on the running container: `docker exec -it  addon_77b2833f_timescaledb bash` 
The file you want to edit is in `/data/postgres`. Nano is already installed as an editor in this addon.
