### ISSUE TITLE
Unable to Connect To DB (Port not listed)

### ISSUE THREAD

**Issue by tylerwmarrs** [Expaso/hassos-addons#6]
I have used your latest instructions to successfully install the add-on, however, it does not appear to open up the PostgreSQL port. See the screenshot below from a nmap scan.

![image](https://user-images.githubusercontent.com/18449075/97068911-655d8100-1591-11eb-81df-113b823db418.png)

Strangely, the logs show that port 5432 is listening.

![image](https://user-images.githubusercontent.com/18449075/97068993-50352200-1592-11eb-954f-62f6e5bcbd7f.png)

**Comment by tylerwmarrs** [comment]
I figured out my issue. You MUST set the listening port in the configuration. Even if you expect it to simply use the default port of 5432. This should probably be updated in the steps of your README.

![image](https://user-images.githubusercontent.com/18449075/97069139-ab1b4900-1593-11eb-8d4d-42ce9a390ac4.png)

**Comment by expaso** [comment]
Hi @tylerwmarrs, good that your issue is resolved!
The screenshot of the logs show you information from within the container. 

To expose that port to the host, you indeed have to explicitly set the port number you want to expose it on (hence, that is why the port-number in the container is fixed to 5432/tcp.

I will add it to the readme.
